//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _COMMUNITY_HARDWARE_SIGNALGENERATOR_H_
#define _COMMUNITY_HARDWARE_SIGNALGENERATOR_H_

#include <TinyCLR_Interop.h>
struct Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator
{
    static const int FIELD___signalInfo = 1;
    static const int FIELD___pin = 2;
    static const int FIELD___invert = 3;
    static const int FIELD___levelTimes = 4;

    TINYCLR_NATIVE_DECLARE(get_PinState___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(set_PinState___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeInitialize___VOID);
    TINYCLR_NATIVE_DECLARE(NativeDispose___VOID);
    TINYCLR_NATIVE_DECLARE(Start___VOID__I4__R8__R8);
    TINYCLR_NATIVE_DECLARE(Start___VOID__mscorlibSystemDateTime__I4__R8__R8);
    TINYCLR_NATIVE_DECLARE(Stop___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_SignalGenerator;

#endif  //_COMMUNITY_HARDWARE_SIGNALGENERATOR_H_
