//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Hardware_SignalGenerator.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::get_PinState___BOOLEAN,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::set_PinState___VOID__BOOLEAN,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::NativeInitialize___VOID,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::NativeDispose___VOID,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::Start___VOID__I4__R8__R8,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::Start___VOID__mscorlibSystemDateTime__I4__R8__R8,
    Library_Community_Hardware_SignalGenerator_Community_Hardware_SignalGenerator::Stop___VOID,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_SignalGenerator =
{
    "Community.Hardware.SignalGenerator", 
    0x950EA5A7,
    method_lookup
};

