//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Hardware_Settings.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Community_Hardware_Settings_Community_Hardware_SystemSettings::get_DebugInterface___STATIC__CommunityHardwareSystemSettingsPort,
    Library_Community_Hardware_Settings_Community_Hardware_SystemSettings::SetDebugInterface___STATIC__VOID__CommunityHardwareSystemSettingsPort,
    Library_Community_Hardware_Settings_Community_Hardware_SystemSettings::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
    NULL,
    Library_Community_Hardware_Settings_Community_Hardware_SystemSettings::WriteConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1,
    Library_Community_Hardware_Settings_Community_Hardware_SystemSettings::ReadConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_Settings =
{
    "Community.Hardware.Settings", 
    0xDAA9AEEB,
    method_lookup
};

