//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _COMMUNITY_HARDWARE_USBHOST_H_
#define _COMMUNITY_HARDWARE_USBHOST_H_

#include <TinyCLR_Interop.h>
struct Library_Community_Hardware_UsbHost_Community_Hardware_UsbHost_UsbController
{
    static const int FIELD_STATIC___defaultController = 0;

    static const int FIELD___dispatcher = 1;

    TINYCLR_NATIVE_DECLARE(NativeStart___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(NativeStop___BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_UsbHost;

#endif  //_COMMUNITY_HARDWARE_USBHOST_H_
