//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Hardware_UsbHost.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Community_Hardware_UsbHost_Community_Hardware_UsbHost_UsbController::NativeStart___BOOLEAN,
    Library_Community_Hardware_UsbHost_Community_Hardware_UsbHost_UsbController::NativeStop___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_UsbHost =
{
    "Community.Hardware.UsbHost", 
    0x7F0B2750,
    method_lookup
};

