//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_System.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Community_System_Community_System_BitConverter::DoubleToInt64Bits___STATIC__I8__R8,
    Library_Community_System_Community_System_BitConverter::Int64BitsToDouble___STATIC__R8__I8,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_System_Community_System_BitConverter::SetBytes___STATIC__VOID__I2__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::SetBytes___STATIC__VOID__I4__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::SetBytes___STATIC__VOID__I8__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::SetBytes___STATIC__VOID__R4__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::SetBytes___STATIC__VOID__R8__SZARRAY_U1__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_System_Community_System_BitConverter::ToSingle___STATIC__R4__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::ToDouble___STATIC__R8__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::ToInt16___STATIC__I2__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::ToInt32___STATIC__I4__SZARRAY_U1__I4,
    Library_Community_System_Community_System_BitConverter::ToInt64___STATIC__I8__SZARRAY_U1__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_System =
{
    "Community.System", 
    0x647602BC,
    method_lookup
};

