//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _COMMUNITY_SYSTEM_H_
#define _COMMUNITY_SYSTEM_H_

#include <TinyCLR_Interop.h>
struct Library_Community_System_Community_System_BitConverter
{
    static const int FIELD_STATIC__IsLittleEndian = 0;

    TINYCLR_NATIVE_DECLARE(DoubleToInt64Bits___STATIC__I8__R8);
    TINYCLR_NATIVE_DECLARE(Int64BitsToDouble___STATIC__R8__I8);
    TINYCLR_NATIVE_DECLARE(SetBytes___STATIC__VOID__I2__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(SetBytes___STATIC__VOID__I4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(SetBytes___STATIC__VOID__I8__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(SetBytes___STATIC__VOID__R4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(SetBytes___STATIC__VOID__R8__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ToSingle___STATIC__R4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ToDouble___STATIC__R8__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ToInt16___STATIC__I2__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ToInt32___STATIC__I4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ToInt64___STATIC__I8__SZARRAY_U1__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_System;

#endif  //_COMMUNITY_SYSTEM_H_
