//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "HAL.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_HAL_GHI_GameO_Display::Initialize___STATIC__BOOLEAN__GHIGameODisplayOrientation__U2__U2,
    Library_HAL_GHI_GameO_Display::WriteRaw___STATIC__BOOLEAN__SZARRAY_U1__I4__I4,
    Library_HAL_GHI_GameO_Display::WriteRaw___STATIC__BOOLEAN__SZARRAY_U2__I4__I4,
    Library_HAL_GHI_GameO_Display::WriteRegister___STATIC__BOOLEAN__U2__U2,
    Library_HAL_GHI_GameO_Display::WriteRegister___STATIC__BOOLEAN__U2,
    Library_HAL_GHI_GameO_Display::FillRect___STATIC__BOOLEAN__U2__U2__U2__U2__U2,
    Library_HAL_GHI_GameO_Display::DrawImage___STATIC__BOOLEAN__SZARRAY_U1__U2__U2__U2__U2__U2__U2__U2__U2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHI_GameO =
{
    "GHI.GameO", 
    0xF4E7FE83,
    method_lookup
};

