//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _HAL_H_
#define _HAL_H_

#include <TinyCLR_Interop.h>
struct Library_HAL_GHI_GameO_Accelerometer
{
    static const int FIELD_STATIC__I2CBus = 0;
    static const int FIELD_STATIC__I2CDevice = 1;
    static const int FIELD_STATIC__Enabled = 2;


    //--//

};

struct Library_HAL_GHI_GameO_Display
{
    static const int FIELD_STATIC__ResetPin = 3;
    static const int FIELD_STATIC__BacklightPin = 4;
    static const int FIELD_STATIC__CurrentOrientation = 5;
    static const int FIELD_STATIC__Width = 6;
    static const int FIELD_STATIC__Height = 7;

    TINYCLR_NATIVE_DECLARE(Initialize___STATIC__BOOLEAN__GHIGameODisplayOrientation__U2__U2);
    TINYCLR_NATIVE_DECLARE(WriteRaw___STATIC__BOOLEAN__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(WriteRaw___STATIC__BOOLEAN__SZARRAY_U2__I4__I4);
    TINYCLR_NATIVE_DECLARE(WriteRegister___STATIC__BOOLEAN__U2__U2);
    TINYCLR_NATIVE_DECLARE(WriteRegister___STATIC__BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(FillRect___STATIC__BOOLEAN__U2__U2__U2__U2__U2);
    TINYCLR_NATIVE_DECLARE(DrawImage___STATIC__BOOLEAN__SZARRAY_U1__U2__U2__U2__U2__U2__U2__U2__U2);

    //--//

};

struct Library_HAL_GHI_GameO_Key
{
    static const int FIELD_STATIC__Up = 8;
    static const int FIELD_STATIC__Left = 9;
    static const int FIELD_STATIC__Down = 10;
    static const int FIELD_STATIC__Right = 11;
    static const int FIELD_STATIC__A = 12;
    static const int FIELD_STATIC__B = 13;
    static const int FIELD_STATIC__C = 14;
    static const int FIELD_STATIC__Power = 15;
    static const int FIELD_STATIC__Start = 16;
    static const int FIELD_STATIC__Enabled = 17;
    static const int FIELD_STATIC__KeyPressed = 18;


    //--//

};

struct Library_HAL_GHI_GameO_Sound
{
    static const int FIELD_STATIC__AudioPowerControl = 19;
    static const int FIELD_STATIC__PWMOut = 20;
    static const int FIELD_STATIC__AudioSwitch = 21;
    static const int FIELD_STATIC__Enabled = 22;


    //--//

};

struct Library_HAL_GHI_GameO_TinyBitmap
{
    static const int FIELD__Data = 1;
    static const int FIELD__Width = 2;
    static const int FIELD__Height = 3;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_GHI_GameO;

#endif  //_HAL_H_
