//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Hardware_AnalogSignalGenerator.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::NativeInitialize___VOID,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::NativeDispose___VOID,
    NULL,
    NULL,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::Start___VOID__I4,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::Start___VOID__mscorlibSystemDateTime__I4,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::Stop___VOID,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::GetChannelCount___STATIC__I4,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::GetPin___STATIC__MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin__MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuAnalogOutputChannel,
    Library_Community_Hardware_AnalogSignalGenerator_Community_Hardware_AnalogSignalGenerator::GetMinClockDivisor___STATIC__U2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_AnalogSignalGenerator =
{
    "Community.Hardware.AnalogSignalGenerator", 
    0xC99987B1,
    method_lookup
};

