//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Graphics.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_Graphics_Community_Graphics_JpegReader::Initialize___VOID__STRING,
    Library_Community_Graphics_Community_Graphics_JpegReader::NativeDispose___VOID,
    NULL,
    Library_Community_Graphics_Community_Graphics_JpegReader::ReadNextLine___BOOLEAN,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Graphics =
{
    "Community.Graphics", 
    0xACA2AF82,
    method_lookup
};

