//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _COMMUNITY_GRAPHICS_H_
#define _COMMUNITY_GRAPHICS_H_

#include <TinyCLR_Interop.h>
struct Library_Community_Graphics_Community_Graphics_JpegReader
{
    static const int FIELD___jpegObj = 1;
    static const int FIELD___fileStream = 2;
    static const int FIELD___width = 3;
    static const int FIELD___height = 4;
    static const int FIELD___line = 5;
    static const int FIELD___lineIndex = 6;

    TINYCLR_NATIVE_DECLARE(Initialize___VOID__STRING);
    TINYCLR_NATIVE_DECLARE(NativeDispose___VOID);
    TINYCLR_NATIVE_DECLARE(ReadNextLine___BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Graphics;

#endif  //_COMMUNITY_GRAPHICS_H_
