//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Community_Hardware_QuadratureEncoder.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::GetIOPinCount___I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::GetIOPin___MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin__I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::GetIOStatus___CommunityHardwareQuadratureEncoderIOStatus__I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::InitOutputCompare___VOID__I4__I4__I4__BOOLEAN,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::InitInputCapture___VOID__I4__BOOLEAN,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::ReleaseIO___VOID__I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::GetQuadratureEncoderChannelCount___I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::GetQuadratureEncoderPinsForChannel___VOID__CommunityHardwareQuadratureEncoderChannel__BYREF_MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin__BYREF_MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::Initialize___VOID,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::Uninitialize___VOID,
    NULL,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::get_Count___I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::set_Count___VOID__I4,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::get_CountEnabled___BOOLEAN,
    Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder::set_CountEnabled___VOID__BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_QuadratureEncoder =
{
    "Community.Hardware.QuadratureEncoder", 
    0x6E881E00,
    method_lookup
};

