//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _COMMUNITY_HARDWARE_QUADRATUREENCODER_H_
#define _COMMUNITY_HARDWARE_QUADRATUREENCODER_H_

#include <TinyCLR_Interop.h>
struct Library_Community_Hardware_QuadratureEncoder_Community_Hardware_QuadratureEncoder
{
    static const int FIELD___dispatcher = 1;
    static const int FIELD___channel = 2;
    static const int FIELD___pin_A = 3;
    static const int FIELD___pin_B = 4;
    static const int FIELD___mode = 5;
    static const int FIELD__IOChanged = 6;

    TINYCLR_NATIVE_DECLARE(GetIOPinCount___I4);
    TINYCLR_NATIVE_DECLARE(GetIOPin___MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin__I4);
    TINYCLR_NATIVE_DECLARE(GetIOStatus___CommunityHardwareQuadratureEncoderIOStatus__I4);
    TINYCLR_NATIVE_DECLARE(InitOutputCompare___VOID__I4__I4__BOOLEAN__I4);
    TINYCLR_NATIVE_DECLARE(InitInputCapture___VOID__I4__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(ReleaseIO___VOID__I4);
    TINYCLR_NATIVE_DECLARE(Initialize___VOID);
    TINYCLR_NATIVE_DECLARE(Uninitialize___VOID);
    TINYCLR_NATIVE_DECLARE(get_Count___I4);
    TINYCLR_NATIVE_DECLARE(set_Count___VOID__I4);
    TINYCLR_NATIVE_DECLARE(get_CountEnabled___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(set_CountEnabled___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetChannelCount___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(GetQuadratureEncoderPinsForChannel___STATIC__VOID__CommunityHardwareQuadratureEncoderChannel__BYREF_MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin__BYREF_MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Community_Hardware_QuadratureEncoder;

#endif  //_COMMUNITY_HARDWARE_QUADRATUREENCODER_H_
